config/owasp/suppressions.xml, dependency-check-suppressions.xml, src/contractTest/java/uk/gov/hmcts/reform/prl/documentgenerator/CdAmApiConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/prl/documentgenerator/PdfGGenerationServiceConsumerTest.java
Added basic PACT tests for status codes
```
[ ] Yes
[x] No
```
=> added pact tests from fprl repo

build.gradle
https://tools.hmcts.net/jira/browse/PRL-663
Merge the BOT PRs for prl-cos-api and prl-dgs-api
prl-dgs-api - Merging BOT PR's - 5,10,11,12,19,20,21
```
[ ] Yes
[x] No
```
=> Prl 663 merge bot pr

src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocumentManagementServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/util/TestData.java
=> fix ignored testcases

src/main/resources/application.yml, src/main/resources/example-application-aat.yml, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocumentManagementServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/util/TestData.java
=> Revert "fix ignored testcases"

src/main/resources/application.yml
=> docmosis access key changed

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml, src/main/resources/example-application-aat.yml
=> Fix s2s auth fail

src/contractTest/java/uk/gov/hmcts/reform/prl/documentgenerator/CdAmApiConsumerTest.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocumentManagementServiceImpl.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocumentManagementServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/util/TestData.java
=> CaseType Changed to PRLAPPS

charts/prl-dgs/Chart.yaml
=> Chart upgrade

src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/management/monitoring/health/HealthCheckITest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocumentManagementServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/util/TestData.java
- [ x] commit messages are meaningful and follow good commit message guidelines
```
[ ] Yes
[ ] No
```
=> Update for unit test coverage and functional test

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/prl-dgs/Chart.yaml, charts/prl-dgs/values.aat.template.yaml, charts/prl-dgs/values.preview.template.yaml, charts/prl-dgs/values.yaml, src/contractTest/resources/application.yml, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/mapper/TemplateDataMapper.java, src/main/resources/application.yml, src/main/resources/bootstrap.yaml, src/main/resources/example-application-aat.yml, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/management/monitoring/health/HealthCheckITest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/mapper/TemplateDataMapperTest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocumentManagementServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/util/TestData.java
=> Merge to master

src/main/resources/application.yml
=> Update Template ID for FL401 Final Welsh

src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/controller/DocumentGenerateDownloadController.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/controller/helper/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/mapper/TemplateDataMapper.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/management/monitoring/health/WebServiceHealthCheckUTest.java
=> Code smell fix

dependency-check-suppressions.xml
=> Dependency suppressed for Spring framework

Jenkinsfile_nightly, config/owasp/suppressions.xml
suppression of dependency issue
```
[ ] Yes
[x] No
```
=> added suppression for nightly test pipeline

config/owasp/suppressions.xml, dependency-check-suppressions.xml
=> suppressed CVE

build.gradle
=> Added tomcat version in the gradle to remove CVE

src/contractTest/java/uk/gov/hmcts/reform/prl/documentgenerator/CdamApiConsumerTest.java
=> Added headers details as per contract with CDAM

build.gradle, config/owasp/suppressions.xml
- [X ] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/FPET-36
Fixed CVE errors and updated suppressions
```
[X ] No
```
=> FPET-36 fixed CVE errors and updated suppressions

src/main/resources/application.yml
=> Prl 1316 fl404a dev

src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-1357
```
[ ] Yes
[x] No
```
=> Prl 1357 docs update

Jenkinsfile_CNP, build.gradle, charts/prl-dgs/Chart.yaml, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/DocumentGenerateControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/RootControllerFunctionalTest.java, src/smokeTest/java/uk/gov/hmcts/reform/prl/DgsApiSmokeTests.java
=> FPET-54 CVE fixes, smoke & functional test fixes

config/owasp/suppressions.xml, src/main/resources/application.yml
=> PRL-1797: Renaming docmosis templates

charts/prl-dgs/Chart.yaml
=> Upgraded helm chart for Java

pacts/prl-dgs-api-CCD_CASE_DOCS_AM_API.json, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/util/ResourceLoaderUTest.java
=> Mutation tests fixed

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/FPET-34
```
[ ] Yes
[ ] No
```
=> FPET-34 DGS changes for C1A & C8 Draft

src/main/resources/application.yml
=> Adding solicitor draft order

build.gradle, charts/prl-dgs/values.preview.template.yaml, config/owasp/suppressions.xml
=> Nightly build fix

build.gradle, charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/FPET-173
```
[ ] Yes
[ ] No
```
=> vulnerability fix for fpet-174

build.gradle
- [X ] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/FPET-179
Upgraded jackson to 2.14.0-rc1to fix Nightly build
```
[ ] Yes
[ X] No
```
=> FPET-179 Upgraded jackson to 2.14.0-rc1to fix Nightly build

src/main/resources/application.yml
PRL-2321,2314,2315
Welsh translation changes
```
[ ] Yes
[x] No
```
=> Welsh template changes

src/main/resources/application.yml
=> Welsh translations for FL402 document

src/main/resources/application.yml
=> Welsh translations for C43 & C43A order document

src/main/resources/application.yml
=> Welsh translation orders C47A

src/main/resources/application.yml
=> Welsh translations for C45A document

build.gradle
=> Add the required versionof dependency

charts/prl-dgs/Chart.yaml
=> Chart upgrade for dgs-api

charts/prl-dgs/values.yaml
https://tools.hmcts.net/jira/browse/PRL-2886
Autoscaling feature added
```
[ ] Yes
[x] No
```
=> Autoscaling

build.gradle
=> Dependency check vulnerabilities fix

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/FPET-364
```
[ ] Yes
[ ] No
```
=> Nightly build issue fix

config/owasp/suppressions.xml
=> Added supressions for CVE

charts/prl-dgs/Chart.yaml, config/owasp/suppressions.xml
=> updated version in charts

Dockerfile, config/owasp/suppressions.xml
=> Upgrade Dockerfile

build.gradle
=> downgrade pact plugin for fixing build issue

src/main/resources/application.yml
=> Added SDO to dgs

config/owasp/suppressions.xml, src/main/resources/application.yml
=> PRL-3101-3049 added templates for C6 and C6a

build.gradle, charts/prl-dgs/Chart.yaml, charts/prl-dgs/values.yaml
=> Infra change

src/main/resources/application.yml
[PRL-3748](https://tools.hmcts.net/jira/browse/PRL-3748)
Welsh cover letter
```
[ ] Yes
[ ] No
```
=> Cover-letter-welsh

src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/domain/response/GeneratedDocumentInfo.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocumentManagementServiceImpl.java, src/main/resources/application.yml, src/smokeTest/java/uk/gov/hmcts/reform/prl/DgsApiSmokeTests.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java
=> Adding static docs

src/main/resources/application.yml
=> C1A Final doc added

config/owasp/suppressions.xml, src/main/resources/application.yml
[PRL-3932](https://tools.hmcts.net/jira/browse/PRL-3932)
Cover letter changes
```
[ ] Yes
[x] No
```
=> Adding access code cover letters

Dockerfile, build.gradle, charts/prl-dgs/Chart.yaml, charts/prl-dgs/values.preview.template.yaml, charts/prl-dgs/values.yaml, checkstyle.xml, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties, lib/applicationinsights.json, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/controller/DocumentGeneratorController.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/management/monitoring/health/HealthCheckITest.java
=> java 17 and gradel 7 upgrade

src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/SNI-4206
SNI-4206 fixed welsh seal for english documents
```
[ ] Yes
[ ] No
```
=> SNI-4206 fixed welsh seal for english documents

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocumentManagementServiceImpl.java, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/FPET-325
AOH & People feature document changes
```
[ ] Yes
[ ] No
```
=> AOH & People feature document changes

src/main/resources/application.yml
=> PRL-LET-ENG-C100-RE5 update name for RE5

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/FPET-695
Fixed CVE by upgrading relevant packages
```
[ ] Yes
[ ] No
```
=> FPET-695 CVE fixes

.github/PULL_REQUEST_TEMPLATE.md, .github/renovate.json, Jenkinsfile_CNP, README.md
=> Renovate inclusion

charts/prl-dgs/Chart.yaml, config/owasp/suppressions.xml
Upgraded chart version as PlatOps enforced changes
```
[ ] Yes
[x] No
```
=> Update helm chart for java node

build.gradle
https://tools.hmcts.net/jira/browse/FPET-809
Updates dependencies to fix CVE issues
```
[ ] Yes
[x] No
```
=> FPET-809: CVE fixes

build.gradle, gradle/wrapper/gradle-wrapper.properties
- [x ] the enable_keep_helm label has been added, if the helm release should be persisted after a successful build
```
[ ] Yes
[ ] No
```
=> increment dependency version

charts/prl-dgs/values.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/mapper/TemplateDataMapper.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/mapper/TemplateDataMapperTest.java
… data
https://tools.hmcts.net/jira/browse/PRL-4981
```
[ ] Yes
[x] No
```
=> PRL-4981 - Added a new key & parsing for temp party names for hearing data

src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-5200
Removing the file names
```
[ ] Yes
[x] No
```
=> Changing the file names

src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-5323
```
[ ] Yes
[ X] No
```
=> PRL-5323: added template for welsh C7

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-4449
```
[ ] Yes
[ ] No
```
=> PRL-4449-DA-List-on-Notice

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
=> PRL-5203-CA-Personal-Service-Unrepresented-Applicant-Post

charts/prl-dgs/values.preview.template.yaml, src/contractTest/resources/application.yml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-2692
added Welsh C7 file properties
```
[ ] Yes
[x] No
```
=> prl_2692_Respondent_Solicitor_C7_Docmosis_Welsh: added Welsh C7 file properties

charts/prl-dgs/values.preview.template.yaml, src/contractTest/resources/application.yml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-2692
https://tools.hmcts.net/jira/browse/PRL-2806
Its now a combined PR of the above tickets
```
[ ] Yes
[x] No
```
=> C1A Welsh - Draft and Final Template

src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-5301
Added RE7 for Citizen Sos
```
[ ] Yes
[ ] No
```
=> Added RE7 for Citizen Sos PRL-5301

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-5465
This change will enable MIAM policy changes and will support both version 2 and version 3 of tasklist
```
[ ] Yes
[x] No
```
=> MIAM EX UI Policy Change

Dockerfile
https://tools.hmcts.net/jira/browse/PRL-5730
Added health check to dgs api
```
[ ] Yes
[x] No
```
=> Fix/health_check: Added health check

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-5300
```
[ ] Yes
[ ] No
```
=> PRL-5300 - Added a new cover letter with access code, needed when legal rep is removed

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-5608
This PR will address english and welsh templates for respondent LiP responding to AoH from applicant
```
[ ] Yes
[x] No
```
=> Respondent respond to AOH

.github/workflows/ci.yml, charts/prl-dgs/Chart.yaml
Changed github permissions.
```
[ ] Yes
[x] No
```
=> Fix/github_read_permissions : Added github read permissions for dgs

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
=> SNI-5901-updated file name for FL404A matching naming convention

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/FPET-909
```
[ ] Yes
[ ] No
```
=> FPET-909 enabled error messages for CA case

README.md, charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
=> Fpet prl 4976

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
=> FPET-931 pointing correct ccd.

README.md, charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
=> FPET-914 changes

build.gradle, charts/prl-dgs/Chart.yaml, charts/prl-dgs/values.preview.template.yaml, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/config/HttpConnectionConfiguration.java
=> FPET-1019: Fix CVE issues

src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/PRL-5979
Added LTR RE7 Welsh template
```
[ ] Yes
[x] No
```
=> PRL-5979 - Added LTR RE7 Welsh template

src/contractTest/resources/application.yml, src/main/resources/application.yml
=> PRL-5974:Added template for DA RE8 letter.

build.gradle, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/config/HttpConnectionConfiguration.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/config/TemplatesConfigurationTest.java
https://tools.hmcts.net/jira/browse/FPET-1120
Removed the reform packages and used the latest one from hmcts git
```
[ ] Yes
[ ] No
```
=> FPET-1120 CI build issues fix

charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/FPET-1144
```
[ ] Yes
[ ] No
```
=> fixed FPET-1144 issues

src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocmosisPdfGenerationServiceImplUTest.java
FPVTL-98
```
[ ] Yes
[x] No
```
=> FPVTL-98 small non change to test pipeline

src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/controller/DocumentGeneratorController.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/mapper/TemplateDataMapper.java, src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocmosisPDFGenerationServiceImpl.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/service/impl/DocmosisPdfGenerationServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/util/NullOrEmptyValidatorUTest.java
[FPET-1031](https://tools.hmcts.net/jira/browse/FPET-1031)
Sonar issues for prl-dgs-api
=> FPET-1031-fixed sonar issues

README.md, charts/prl-dgs/values.preview.template.yaml, src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/FPET-1138
```
[ ] Yes
[ ] No
```
=> FPET-1138 renaming templates for send message

.github/renovate.json
=> FPVTL-837 Update renovate.json
